name: rebooked_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.10+1
  smooth_page_indicator: ^1.1.0
  country_picker: ^2.0.21
  pinput: ^4.0.0
  percent_indicator: ^4.2.3
  another_xlider: ^3.0.2
  bottom_picker: ^2.7.0
  google_maps_flutter: ^2.5.0
  flutter_rating_bar: ^4.0.1
  dotted_border: ^2.1.0
  dotted_line: ^3.2.2
  salomon_bottom_bar: ^3.3.2
  persistent_bottom_nav_bar: ^5.0.2



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true


  assets:
    - assets/images/
    - assets/images/on_boarding/
    - assets/icons/
    - assets/icons/bottom/


  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Thin.ttf
          weight: 100
        - asset: assets/fonts/Lato-Light.ttf
          weight: 300
        - asset: assets/fonts/Lato-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lato-Black.ttf
          weight: 900